package common

const RESULT_STATUS_SUCCESS = "SUCCESS"
const RESULT_STATUS_FAIL = "FAIL"

const EMPTY_STR = "-"

const OK = "OK"
const ALL_NAMESPACE = "all"
const LIST_RELEASES = "LIST_RELEASES"
const NAMESPACE_ALL_NOT_ALLOWED = "NAMESPACE_ALL_NOT_ALLOWED"

// VAULT
const FAILED_TO_READ_CLUSTER_INFO = "FAILED_TO_READ_CLUSTER_INFO"
const FAILED_TO_PARSE_VALUES = "FAILED_TO_PARSE_VALUES"

// REPOSITORY
const REPO_NAME_URL_REQUIRED = "REPO_NAME_URL_REQUIRED"
const REPO_NAME_CONTAINS_SC = "REPO_NAME_CONTAINS_SC"
const REPO_NAME_ALREADY_EXISTS = "REPO_NAME_ALREADY_EXISTS"
const REPO_NAME_PATTERN_NOT_ALLOWED = "REPO_NAME_PATTERN_NOT_ALLOWED"
const REPO_USERNAME_PASSWD_REQUIRED = "REPO_USERNAME_PASSWD_REQUIRED"
const REPO_SAME_CONF_ALREADY_EXISTS = "REPO_SAME_CONF_ALREADY_EXISTS"
const REPO_CANNOT_BE_REACHED = "REPO_CANNOT_BE_REACHED"
const REPO_NO_CONFIGURED = "REPO_NO_CONFIGURED"
const REPO_NO_NAMED_FOUND = "REPO_NO_NAMED_FOUND"
const REPO_UNABLE_UPDATE = "REPO_UNABLE_UPDATE"
const REPO_FAILED_LOADING_FILE = "REPO_FAILED_LOADING_FILE"
const REPO_CORRUPT_MISSING = "REPO_CORRUPT_MISSING"
const REPO_CA_INVALID = "REPO_CA_INVALID"
const REPO_CA_FAILED_SAVE = "REPO_CA_FAILED_SAVE"
const REPO_CA_ALREADY_EXISTS = "REPO_CA_ALREADY_EXISTS"
const REPO_CONNECT_TIMEOUT = "REPO_CONNECT_TIMEOUT"
const INSTALLATION_FAILED = "INSTALLATION_FAILED"

const CHART_INFO_INVALID = "CHART_INFO_INVALID"
const CHART_VERSION_INVALID = "CHART_VERSION_INVALID"
const REVISION_NUMBER_INVALID = "REVISION_NUMBER_INVALID"

const CHART_NOT_FOUND = "CHART_NOT_FOUND"
const RELEASE_NOT_FOUND = "RELEASE_NOT_FOUND"
const RELEASE_ALREADY_EXISTS = "RELEASE_ALREADY_EXISTS"

const LIMIT_VAL_INVALID = "LIMIT_VAL_INVALID"
const OFFSET_VAL_INVALID = "OFFSET_VAL_INVALID"
const LIMIT_ILLEGAL_ARGUMENT = "LIMIT_ILLEGAL_ARGUMENT"
const OFFSET_ILLEGAL_ARGUMENT = "OFFSET_ILLEGAL_ARGUMENT"
const OFFSET_REQUIRES_LIMIT_ILLEGAL_ARGUMENT = "OFFSET_REQUIRES_LIMIT_ILLEGAL_ARGUMENT"
const HUB_PACKAGE_LIMIT_ILLEGAL_ARGUMENT = "HUB_PACKAGE_LIMIT_ILLEGAL_ARGUMENT"

const NOT_FOUND = "NOT_FOUND"
const TOKEN_FAILED = "TOKEN_FAILED"
const TOKEN_EXPIRED = "TOKEN_EXPIRED"
const MISSING_OR_MALFORMED_JWT = "MISSING_OR_MALFORMED_JWT"
const REPO_NAME_REGEXP_PATTERN = "^[a-zA-Z0-9_-]{1,50}$"

const AUTH_SUPER_ADMIN = "SUPER_ADMIN"
const AUTH_CLUSTER_ADMIN = "CLUSTER_ADMIN"
const AUTH_USER = "USER"
